import { Inter } from "next/font/google"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Zhafirah Admin",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{ baseTheme: dark, elements: { footer: "hidden" } }}
    >
      <html lang="en">
        <body className={`${inter.className} text-textColor bg-bgColor`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
